# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Karstens Blog
email: mail@kalehmann.de
author: Karsten Lehmann
website: https://kalehmann.de/
description: >- # this means to ignore newlines until "baseurl:"
  Das ist mein Blog. Hier schreibe ich über alle Projekte, die mich in meiner
  Freizeit beschäftigen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.kalehmann.de" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kalehmann
twitter_username: lehmann_ka

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %H:%M:%S"

# set timezone
timezone: Europe/Berlin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - _posts/embedded/*
 - assets/*/RAW_ASSETS/*
 - assets/*/raw/*
 - scripts
 - Gemfile
 - Gemfile.lock
 - Readme.markdown

# Set the image for the Open Graph Protocol
image:
  path: /assets/favicons/android-chrome-192x192.png
  height: 192
  width: 192

